---
- name: Playbook test to create gce instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars: 
    service_account_email: xxxxx@ultimate-figure-221821.iam.gserviceaccount.com
    credentials_file: ultimate-figure-xxxx.json
    project_id: ultimate-figure-xxxx
    machine_type: n1-standard-1
    image: centos-7

  tasks:
  - name: Lunch instances
    gce:
      instance_names: web01
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      zone: us-east1-b
      metadata: '{"sshKeys":"mygmailuser:ssh-rsa ...."}'
