---
- name: Create gce webserver instance
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    service_account_email: xxxxx@ultimate-figure-xxxxx.gserviceaccount.com
    credentials_file: ultimate-figure-xxxx.json
    project_id: ultimate-figure-xxxx
    instance_names: web1,web2,web3
    machine_type: n1-standard-1
    image: centos-7

  tasks:
  - name: Create firewall rule to alow http trafic
    gce_net:
      name: default
      fwname: "my-http-fw-rule"
      allowed: tcp:80
      state: present
      src_range: "0.0.0.0/0"
      target_tags: "http-server"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: Create an Instance based on image {{ image }}
    gce:
      instance_names: "{{ instance_names }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      state: present
      preemptible: True
      tags: http-server,https-server
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      zone: us-east1-b
      metadata: '{"sshKeys":"midgardo:ssh-rsa ..."}'
    register: gce

  - name: Save host data within a Group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_temp
    with_items: "{{ gce.instance_data }}"

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
    with_items: "{{ gce.instance_data }}"

  - name: Settings ip as instance fact
    set_fact: host={{ item.public_ip }}
    with_items: "{{ gce.instance_data }}"


- name: Configure instance post-creation
  hosts: gce_instances_temp
  gather_facts: True
  remote_user: mygmailuser
  become: yes
  become_method: sudo

  roles:
    - apache_lab
