---
#replace line, example: 10.10.10.10 my-satellite.lab my-satellite -- > REMOVE this line
- name: Set hostname
  hosts: servers
  tasks:
  - name: Add Satellite host
    lineinfile:
      path: /etc/hosts
      line: 'IP hostname_fqdn hostame' 
      state: present
