#name of the VM will be picked up from the ip address last octet xxx.xxx.xxx.XXX
- name: Set hostname
  hosts: servers
  vars:
    hostname: vm-*.tsmx.lab
  tasks:
    - name: set the friendly hostname
      hostname: name={{ hostname.replace('*', ansible_all_ipv4_addresses[0].split('.')[3]) }}
